name: Workflow - Ad-hoc run
on:
  workflow_dispatch:

jobs:
  run:
    name: Job - run
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/nuclei_runner:latest

      credentials:
        username: ${{ github.actor }} # provided by Github
        password: ${{ secrets.GITHUB_TOKEN }} # provided by Github

      env:
        APP_ENV: production
        LOG_LEVEL: info
        # Nuclei API key for free and anonymous uploads to Nuclei's cloud  ("Project Discovery, PDCP")
        # pulled from repo/org secrets
        PDCP_API_KEY: ${{ secrets.PDCP_API_KEY }}

    steps:
      - name: Checking in.
        run: |
          # Now we are inside the container
          echo "Morning. We're in $APP_ENV, log level $LOG_LEVEL."

      # By default we use the targets.txt in the repo (filled by default with test domains)
      - name: Check out that code.
        uses: actions/checkout@v4

      - name: Perform run.
        run: |
          nuclei -list targets/targets.txt -cloud-upload

# TODO: Extra hardening
# Pin by digest to avoid surprise upgrades:
# After pushing, capture digest: docker inspect ghcr.io/OWNER/myapp:latest --format='{{index .RepoDigests 0}}'
# Use that digest in your cron (image: ghcr.io/OWNER/myapp@sha256:...).
# Promote via tags: build pushes :sha, then retag :prod only after tests pass; cron runs :prod.
# Retention: set GHCR retention/cleanup so older SHAs don’t vanish before cron needs them.
