name: Workflow - Run
on: push

jobs:
  run:
    name: Job - run
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/sandbox:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        APP_ENV: production
        LOG_LEVEL: info
        # API_TOKEN: ${{ secrets.API_TOKEN }}   # pulled from repo/org secrets
    steps:
      - name: Perform run.
        run: |
          # Now we are inside the container
          echo "Morning. We're in $APP_ENV, log level $LOG_LEVEL."

# TODO: Extra hardening
# Pin by digest to avoid surprise upgrades:
# After pushing, capture digest: docker inspect ghcr.io/OWNER/myapp:latest --format='{{index .RepoDigests 0}}'
# Use that digest in your cron (image: ghcr.io/OWNER/myapp@sha256:...).
# Promote via tags: build pushes :sha, then retag :prod only after tests pass; cron runs :prod.
# Retention: set GHCR retention/cleanup so older SHAs don’t vanish before cron needs them.
