name: Workflow - Run
on:
  push:
  schedule:
    - cron: "0 14 * * *" # Run every day at 14:00 UTC.
  workflow_dispatch:
    inputs:
      targetFile:
        description: "file with targets, located in repo"
        required: true
        default: "test_targets.txt"
        type: string

jobs:
  run:
    name: Job - run
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/nuclei_runner:latest
      credentials:
        username: ${{ github.actor }} # provided by Github
        password: ${{ secrets.GITHUB_TOKEN }} # provided by Github
      env:
        APP_ENV: production
        LOG_LEVEL: info
        # API_TOKEN: ${{ secrets.API_TOKEN }}   # pulled from repo/org secrets
    steps:
      - name: Perform run.
        run: |
          # Now we are inside the container
          echo "Morning. We're in $APP_ENV, log level $LOG_LEVEL."
          echo "Here we will gather the list of targets, maybe in render_targets.sg or smth, and forward them to nuclei"
          echo "Starting Nuclei scan of targets.txt"
          nuclei -u targets.txt

# TODO: Extra hardening
# Pin by digest to avoid surprise upgrades:
# After pushing, capture digest: docker inspect ghcr.io/OWNER/myapp:latest --format='{{index .RepoDigests 0}}'
# Use that digest in your cron (image: ghcr.io/OWNER/myapp@sha256:...).
# Promote via tags: build pushes :sha, then retag :prod only after tests pass; cron runs :prod.
# Retention: set GHCR retention/cleanup so older SHAs don’t vanish before cron needs them.
