name: Workflow - Scheduled daily run
on:
  schedule:
    - cron: "0 14 * * *" # Run every day at 14:00 UTC.
  workflow_dispatch:

jobs:
  run:
    name: Job - run
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/${{ github.repository_owner }}/nuclei_runner:latest

      credentials:
        username: ${{ github.actor }} # provided by Github
        password: ${{ secrets.GITHUB_TOKEN }} # provided by Github

      env:
        APP_ENV: production
        LOG_LEVEL: info
        # Nuclei API key for free and anonymous uploads to Nuclei's cloud  ("Project Discovery, PDCP") 
        # pulled from repo/org secrets
        PDCP_API_KEY: ${{ secrets.PDCP_API_KEY }} 

    steps:
      - name: Checking in.
        run: |
          # Now we are inside the container
          echo "Morning. We're in $APP_ENV, log level $LOG_LEVEL."

      - name: Check out that code and them schedules.
        uses: actions/checkout@v4

      - name: Gather target list, based on the day of the week.
        run: |
          # Get the day of the week
          day_of_week=$(date +%u)
          echo "Day of the week: $day_of_week"

          # Get the number of the day of the week
          day_of_week_number=$(date +%u)
          echo "Day of the week number: $day_of_week_number"

          # Write the target list to a file
          cp targets/$day_of_week_number_$day_of_week.yaml targets/targets.txt


      - name: Perform run.
        run: |
          nuclei -list targets.txt -cloud-upload

# TODO: Extra hardening
# Pin by digest to avoid surprise upgrades:
# After pushing, capture digest: docker inspect ghcr.io/OWNER/myapp:latest --format='{{index .RepoDigests 0}}'
# Use that digest in your cron (image: ghcr.io/OWNER/myapp@sha256:...).
# Promote via tags: build pushes :sha, then retag :prod only after tests pass; cron runs :prod.
# Retention: set GHCR retention/cleanup so older SHAs don’t vanish before cron needs them.
